language: java


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

install: gradle build -x test
script: gradle jar
